"""Builds website/ from the last demo run."""
from __future__ import annotations
import pathlib
from . import sitekit as sk

ROOT = pathlib.Path(__file__).resolve().parent.parent
META = {
    "name": "Contagion Observatory",
    "slug": "contagion-observatory",
    "repo": "3.0-Financial-Ai-Systems",
    "pillar": "Financial Stability",
    "tagline": "Which crypto-equity links actually TRANSMIT stress, separated from the "
               "much larger set that merely move together — and what a shock to one "
               "asset does to the rest.",
    "tags": [("tail dependence", ""), ("factor removal", ""),
             ("directed lead-lag", ""), ("constructed ground truth", "demo")],
    "banner": "The market here is synthetic, generated by src/market.py with a KNOWN "
              "set of transmitting edges. That is the point: correlation is everywhere "
              "in real market data and almost none of it is transmission, so a "
              "contagion method has to be tested where the true links are known. No "
              "real asset universe has been analysed.",
}


def build_site(results: dict) -> pathlib.Path:
    u, b = results["universe"], results["best"]
    dc, shocks = results["design_comparison"], results["shocks"]
    winner = dc[0]

    metrics = sk.metric_grid([
        ("Assets", u["n_assets"], f"{u['n_crypto']} crypto / {u['n_equity']} equity"),
        ("Ordered pairs", u["n_candidate_pairs"], f"{u['n_true_edges']} truly linked"),
        ("Recall", f"{b['recall']:.0%}", f"{b['tp']} of {u['n_true_edges']} found"),
        ("Precision", f"{b['precision']:.2f}", f"{b['fp']} false candidates"),
    ])

    design_tbl = sk.table(
        ["Scorer", "Returns", "Best F1", "Precision", "Recall", "Median rank of true edges"],
        [[r["scorer"], r["returns"], f"{r['best_f1']:.3f}", f"{r['precision']:.3f}",
          f"{r['recall']:.3f}", r["median_rank"]] for r in dc],
        numeric_cols=(2, 3, 4, 5))

    resid = {x["pair"]: x["tail_lift"] for x in results["tail_residual"]}
    tail_tbl = sk.table(
        ["Pair", "Link type", "Tail lift — raw", "Tail lift — residual"],
        [[r["pair"], r["kind"], f"{r['tail_lift']:.2f}",
          f"{resid.get(r['pair'], float('nan')):.2f}"]
         for r in results["tail_raw"]],
        numeric_cols=(2, 3))

    sweep = results["sweep"]
    pr_chart = sk.line_chart(
        [("precision", [(i, r["precision"]) for i, r in enumerate(sweep)]),
         ("recall", [(i, r["recall"]) for i, r in enumerate(sweep)]),
         ("F1", [(i, r["f1"]) for i, r in enumerate(sweep)])],
        xlabel="threshold step (looser → stricter)", ylabel="score")

    edge_tbl = sk.table(
        ["Source", "Target", "Strength", "Active"],
        [[e["src"], e["dst"], e["strength"],
          "stress only" if e["stress_only"] else "always"]
         for e in results["true_edges"]], numeric_cols=(2,))

    top_tbl = sk.table(
        ["Rank", "Source", "Target", "Lagged corr", "Tail lift", "Score", "Real?"],
        [[i + 1, r["src"], r["dst"],
          f"{r['lagged_corr']:.4f}" if r["lagged_corr"] is not None else "—",
          f"{r['tail_lift']:.2f}" if r["tail_lift"] is not None else "—",
          f"{r['score']:.4f}",
          "yes" if any(e["src"] == r["src"] and e["dst"] == r["dst"]
                       for e in results["true_edges"]) else "no"]
         for i, r in enumerate(results["top_edges"])],
        numeric_cols=(0, 3, 4, 5))

    shock_tbl = sk.table(
        ["Shocked asset", "Assets reached", "Total absolute impact", "Path"],
        [[k, v["n_reached"], f"{v['total_absolute_impact']:.4f}",
          " → ".join(v["reached"][:5]) or "nothing"] for k, v in shocks.items()],
        numeric_cols=(1, 2))

    body = f"""
<section>
  <h2>Correlation is not transmission</h2>
  <div class="stack">
    <p>A common factor makes every asset move together with no causal link at all, and
    in a crypto-equity panel that factor is large. So a correlation-based edge set is
    mostly false edges, and the whole problem is separating the two.</p>
    <p>Two things do it. Removing the first principal component strips the shared
    factor, leaving residual co-movement where a real link shows up. And using a
    <em>lagged</em> correlation makes the measure directional, which a contemporaneous
    correlation can never be.</p>
  </div>
</section>

<section>
  <h2>This run</h2>
  <div class="stack-lg">
    {metrics}
    <p class="mono" style="color:var(--muted);font-size:12.5px">
      generated {sk.esc(results['generated_at'])} &middot; {u['n_days']} days &middot;
      {u['stress_days']} stress days ({u['stress_share']:.0%}) &middot;
      {u['n_true_edges']} constructed edges
    </p>
    {edge_tbl}
  </div>
</section>

<section>
  <h2>Tail dependence measures the factor, not the link</h2>
  <div class="stack-lg">
    {tail_tbl}
    <div class="note">
      <h3>Read the last two columns against each other</h3>
      <p>On <strong>raw returns</strong>, unlinked pairs show a tail lift of
      {[r for r in results['tail_raw'] if r['kind'] == 'none'][0]['tail_lift']:.2f} —
      <em>higher</em> than most of the genuinely linked pairs. Everything crashes
      together because everything loads on the same factor, so tail dependence measured
      on raw prices carries no information about transmission whatsoever.</p>
      <p>On <strong>factor-removed residuals</strong>, unlinked pairs fall to
      {resid.get('unlinked pairs (mean of 60)', 0):.2f} while real links survive at up
      to {max(v for k, v in resid.items() if 'unlinked' not in k):.2f}. This is the
      single most important number on the page: a tail-dependence figure quoted without
      the factor removed is not evidence of contagion.</p>
    </div>
  </div>
</section>

<section>
  <h2>The design that lost</h2>
  <div class="stack-lg">
    {design_tbl}
    <div class="note">
      <h3>Multiplying by tail lift was the original design, and it is worse</h3>
      <p>Scoring each pair as |lagged correlation| × tail lift seemed obviously right:
      combine a directional signal with a stress-specific one. It ranks the true edges
      at a median position of
      {[r for r in dc if r['scorer'] == 'product' and r['returns'] == 'factor removed'][0]['median_rank']}
      out of {u['n_candidate_pairs']}. Lagged correlation <em>alone</em> ranks them at
      {winner['median_rank']}.</p>
      <p>The reason is visible in the table above: on residuals, several genuine links
      have tail lift <em>below</em> 1, so the multiplier suppresses exactly the edges it
      was added to surface. The whole grid is published rather than only the winning
      row, because reporting the configuration that worked without the ones tried first
      presents a searched result as a derived one.</p>
    </div>
    {pr_chart}
  </div>
</section>

<section>
  <h2>What the ranking actually looks like</h2>
  <div class="stack-lg">
    {top_tbl}
    <p>At the best threshold the method finds <strong>{b['tp']} of {u['n_true_edges']}</strong>
    real links and surfaces <strong>{b['fp']}</strong> false candidates alongside them.
    That is a screening tool, not a detector: it takes {u['n_candidate_pairs']} ordered
    pairs down to roughly {b['n_selected']} worth a human look, and does not miss a real
    link in doing so. Precision of {b['precision']:.2f} is the honest cost, and quoting
    the recall without it would misdescribe what the method does.</p>
  </div>
</section>

<section>
  <h2>Shock propagation</h2>
  <div class="stack-lg">
    {shock_tbl}
    <div class="note">
      <h3>Two choices worth stating</h3>
      <p>Shocks propagate through the <em>constructed</em> edge set, not the estimated
      one. Pushing a shock through estimated edges compounds estimation error into a
      confident-looking fan-out that is mostly artefact, and it conflates two separate
      questions: can the network be recovered, and given a network, what does a shock do.</p>
      <p>Only newly-received impact re-transmits. An earlier version carried each node's
      accumulated total forward every round, so nodes re-emitted their whole balance and
      a 20% shock produced 104% of total absolute impact — five times the energy that
      entered the system. It now decays, as it must.</p>
    </div>
  </div>
</section>

<section>
  <h2>Reproduce it</h2>
  <div class="stack">
    <pre>cd contagion-observatory
pip install -r requirements.txt
python -m pytest tests/ -q
python -m src.demo</pre>
    <p>For real data, replace <code>src/market.py</code> with a loader returning a
    returns matrix and asset classes. Everything in <code>src/contagion.py</code> is
    unchanged — but note that a real panel has no ground-truth edge set, so the
    recovery scores on this page have no real-data equivalent.</p>
  </div>
</section>

<section>
  <h2>What this does not establish</h2>
  <div class="stack">
    <ul class="tight">
      <li>No real assets have been analysed. There is no 7,500-crypto or 6,000-equity
      universe behind any figure here.</li>
      <li>The generator was written by the same person as the method, and it embeds
      the linear lagged structure the method looks for. Real transmission is not
      linear and not one-day-lagged.</li>
      <li>Recovery scores exist only because the edges were constructed. On real
      data there is no ground truth, so the method can be validated only indirectly
      — against known episodes, or out of sample.</li>
      <li>Precision at best threshold is {b['precision']:.2f}. This is a screening
      tool that hands a human a shortlist, not something to act on unsupervised.</li>
      <li>Propagation is a linear cascade with no capital constraints, no
      liquidation dynamics and no feedback. It shows reachability, not loss.</li>
    </ul>
  </div>
</section>
"""
    return sk.build(ROOT, META, body, results)
