"""Builds website/ from the last demo run."""
from __future__ import annotations
import pathlib
from . import sitekit as sk

ROOT = pathlib.Path(__file__).resolve().parent.parent
META = {
    "name": "Tokenized Fixed-Income Analytics",
    "slug": "tokenized-fixed-income-analytics",
    "repo": "3.0-Financial-Ai-Systems",
    "pillar": "Financial Stability",
    "tagline": "Liquidity, holder concentration and redemption latency for tokenised "
               "debt, measured from a trade tape and a holder snapshot — the only "
               "inputs that survive a thin, irregular market.",
    "tags": [("Amihud + Roll", ""), ("HHI / effective holders", ""),
             ("redemption queue", ""), ("synthetic chain data", "demo")],
    "banner": "Every figure comes from a synthetic on-chain history generated by "
              "src/chain.py, built so each measure can be checked against a property "
              "that was deliberately put there. No real chain data is used, and the "
              "absolute levels below carry no information about any real token.",
}


def build_site(results: dict) -> pathlib.Path:
    toks = results["tokens"]
    rc = results["recovery"]
    st = results["stress"]

    metrics = sk.metric_grid([
        ("Tokens", results["universe_size"], "spanning the liquidity range"),
        ("Trades", f"{results['total_trades']:,}", "synthetic tape"),
        ("Redemptions", f"{results['total_redemptions']:,}", "with settlement lags"),
        ("Stress latency", f"{st['median_latency_ratio']:.1f}×",
         "median queue lengthening"),
    ])

    main_tbl = sk.table(
        ["Token", "Wallets", "Effective holders", "Top-5 share", "Gini",
         "Amihud ×10⁶", "Roll (bps)", "p95 gap (h)"],
        [[t["symbol"], t["concentration"]["n_wallets"],
          f"{t['concentration']['effective_holders']:.1f}",
          f"{t['concentration']['top5_share']:.1%}",
          f"{t['concentration']['gini']:.3f}",
          f"{t['liquidity']['amihud_x1e6']:.3f}",
          (f"{t['liquidity']['roll_spread_bps']:.0f}"
           if t["liquidity"]["roll_spread_bps"] is not None else "n/a"),
          f"{t['liquidity']['p95_gap_h']:.1f}"] for t in toks],
        numeric_cols=(1, 2, 3, 4, 5, 6, 7))

    amihud_chart = sk.bar_chart(
        [(t["symbol"], t["liquidity"]["amihud_x1e6"]) for t in toks], fmt="{:.3f}")
    holders_chart = sk.bar_chart(
        [(t["symbol"], t["concentration"]["effective_holders"]) for t in toks],
        fmt="{:.0f}")

    stress_rows = [[t["symbol"], t["stress"]["n_inside"],
                    f"{t['stress']['median_outside_h']:.1f}",
                    f"{t['stress']['median_inside_h']:.1f}",
                    f"{t['stress']['ratio']:.1f}×"]
                   for t in toks if t["stress"]["n_inside"]]
    stress_tbl = sk.table(
        ["Token", "Requests in window", "Calm median (h)", "Stress median (h)",
         "Ratio"], stress_rows, numeric_cols=(1, 2, 3, 4))

    rec_chart = sk.line_chart(
        [("effective holders", [(r["alpha"], r["effective_holders"])
                                for r in rc["sweep"]])],
        xlabel="Pareto α (higher = more even)", ylabel="effective holders")

    body = f"""
<section>
  <h2>What can be measured from a chain</h2>
  <div class="stack">
    <p>Tokenised debt does not trade every minute and has no consolidated order book,
    so anything needing a regular grid or quote depth is unusable. Every measure here
    works from two inputs a chain actually provides: a trade tape and a holder
    snapshot.</p>
    <p>Concentration is reported as <strong>effective holders</strong> (1/HHI) rather
    than as an index. An HHI of 0.05 means the float behaves as though held by twenty
    equal holders, however many wallets appear on chain — and wallet count is exactly
    the number that misleads, since one holder can hold many wallets and often does.</p>
  </div>
</section>

<section>
  <h2>This run</h2>
  <div class="stack-lg">
    {metrics}
    <p class="mono" style="color:var(--muted);font-size:12.5px">
      generated {sk.esc(results['generated_at'])} &middot;
      {sk.esc(results['data_source'])}
    </p>
    {main_tbl}
  </div>
</section>

<section>
  <h2>Liquidity</h2>
  <div class="stack-lg">
    {amihud_chart}
    <div class="note">
      <h3>This measure was inverted until the generator was fixed</h3>
      <p>The first version of the chain model drew every token's per-trade return from
      the same distribution, so order size carried no price impact. Amihud is a
      price-impact measure, so with no impact to find it read pure noise — and ranked
      the thinnest token in the universe as the <em>most</em> liquid.</p>
      <p>Giving each token a depth parameter, so the same order moves a thin token
      further, restored the ordering shown above: it now runs monotonically from
      STABLE-X at {toks[-1]['liquidity']['amihud_x1e6']:.3f} to MUNI-A at
      {[t for t in toks if t['symbol'] == 'MUNI-A'][0]['liquidity']['amihud_x1e6']:.3f}.
      A metric that cannot recover a property you deliberately built is not measuring
      that property, and this is the check that caught it.</p>
    </div>
    <p>Roll's spread is estimated from the autocovariance of price changes. When that
    autocovariance comes out positive the bid-ask-bounce model does not apply, and the
    function returns <code>n/a</code> rather than a fabricated number — which happens
    in strongly trending markets and is a real limitation of the estimator.</p>
  </div>
</section>

<section>
  <h2>Concentration</h2>
  <div class="stack-lg">
    {holders_chart}
    {rec_chart}
    <p>Sweeping the Pareto tail parameter and confirming the measure moves with it
    is the concentration equivalent of the Amihud check. It is monotone across the
    sweep ({"confirmed" if rc["monotone_in_alpha"] else "NOT MONOTONE"}), so the index
    is tracking the thing it is named after.</p>
  </div>
</section>

<section>
  <h2>The redemption queue is the run indicator</h2>
  <div class="stack-lg">
    {stress_tbl}
    <div class="note">
      <h3>Why this is the measure that matters</h3>
      <p>For a debt token, the queue lengthening is what turns a liquidity problem into
      a run, and it is <em>invisible in the price</em>. Across the tokens with a stress
      episode, median settlement latency rises by a factor of
      {st['median_latency_ratio']:.1f} while the tape keeps printing.</p>
      <p>STABLE-X has no stress episode in the generator and shows a ratio near 1,
      which is the control: a measure that fired on it would be responding to something
      other than stress.</p>
    </div>
  </div>
</section>

<section>
  <h2>Reproduce it</h2>
  <div class="stack">
    <pre>cd tokenized-fixed-income-analytics
pip install -r requirements.txt
python -m pytest tests/ -q
python -m src.demo</pre>
    <p>To run on real data, replace <code>src/chain.py</code> with a loader returning
    <code>TokenHistory</code> objects from an indexer. Nothing in
    <code>src/analytics.py</code> changes.</p>
  </div>
</section>

<section>
  <h2>What this does not establish</h2>
  <div class="stack">
    <ul class="tight">
      <li>No real token has been analysed. The generator was written to exhibit the
      properties the measures look for, so agreement between them is a soundness
      check on the code, not a finding about any market.</li>
      <li>Holder concentration from wallet balances is a lower bound on true
      concentration. One beneficial holder can hold many wallets, and nothing on
      chain distinguishes that from many holders.</li>
      <li>Redemption latency here is generated, not observed. Real settlement
      depends on the issuer's operational process, which is off chain and mostly
      unobservable.</li>
      <li>No regulatory or systemic-risk conclusion follows from synthetic data.</li>
    </ul>
  </div>
</section>
"""
    return sk.build(ROOT, META, body, results)
